package enums;

public enum MessageKey {
    ERROR,
    ASK_NAME,
    MOVED_LEFT,
    MOVED_RIGHT,
    MOVED_STRAIGHT,
    WELCOME,
    ASK_TUTORIAL,
    TUTORIAL_INTRO,
    LIST_COMMANDS_HEADER,
    LIST_COMMANDS_FOOTER,
    END_CONFIRMATION,
    ANOTHER_GAME,
    FOUND_OBJECT,
    WIN,
    FAILURE,
    PATH_BLOCKED,
    FAILED_SAVING,
    SUCCESSFUL_SAVING,
    BACK_IN_GAME,
    LOADING_NEW_GAME,
    SUCCESSFUL_LOADING,
    FAILED_LOADING,
    SAVE_INSTRUCTION,
    UNSETTLING_MESSAGE
}
